target 'iosApp' do
  use_frameworks!
  platform :ios, '18.0'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"
    end
  end
end