name: Setup Lightsaber CI
description: Setup Lightsaber CI
runs:
  using: "composite"
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: 'gradle'
    - name: Shared Build Cache
      uses: actions/cache@v3
      with:
        key: build-shared-${{ github.sha }}
        path: |
          shared/build

    - name: Android App Build Cache
      uses: actions/cache@v3
      with:
        key: build-android-${{ github.sha }}
        path: |
          androidApp/build

    - name: iOS App Build Cache
      uses: actions/cache@v3
      with:
        key: build-ios-${{ github.sha }}
        path: |
          build