name: Lightsaber CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: lightsaber-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-androidApp:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-lightsaber-ci

      - name: Build Android App
        run: ./gradlew :android:app:build

  build-iosApp:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-lightsaber-ci

      - name: Build iOS App
        run: cd ios/app && swift build
