name: Lightsaber CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: lightsaber-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-shared:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-lightsaber-ci

      - name: Build Shared
        # TODO Understand why compileIosMainKotlinMetadata fails every time
        run: ./gradlew shared:build -x compileIosMainKotlinMetadata

  build-androidApp:
    runs-on: macos-latest
    needs: build-shared
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-lightsaber-ci

      - name: Build Android App
        run: ./gradlew androidApp:build

  build-debug-iosApp:
    runs-on: macos-latest
    needs: build-shared
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-lightsaber-ci

      - name: Shared Pod Install
        run: ./gradlew shared:podInstall

      # TODO Setup xcodebuild command correctly
      # - name: Build Debug iOS App
        # run: xcodebuild -workspace ./iosApp/iosApp.xcworkspace -scheme iosApp -configuration Debug |
        #  OBJROOT=./build/ios SYMROOT=./build/ios -arch arm64 -allowProvisioningUpdates

  test-shared:
    runs-on: macos-latest
    needs: build-shared
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-lightsaber-ci

      - name: Unit Test Shared
        run: ./gradlew shared:cleanAllTests shared:allTests

  e2e-test-androidApp:
    runs-on: macos-latest
    needs: build-androidApp
    steps:
      - uses: actions/checkout@v3

      - name: Maestro Cache
        uses: actions/cache@v3
        with:
          key: maestro
          path: $HOME./maestro

      - name: AVD Cache
        uses: actions/cache@v3
        with:
          key: avd
          path: $HOME./avd

      - name: Install or Upgrade Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Add maestro to path
        run: echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Start Android Emulator
        run: maestro start-device --os-version 33 --platform android

      - name: Run Android E2E Tests
        run: maestro test e2eTests